### ISSUE TITLE
I hope you add some for JAVA devs

### ISSUE THREAD

**Issue by steven7mwesigwa** [bnb/awesome-developer-streams#110]
I noticed i could only see [nmarulo](https://www.twitch.tv/nmarulo) in your list specifically for JAVA.
I hope there is more.

**Comment by Adron** [comment]
Do you know of any? You could submit some you've found too!  :)

I'll go look for some too. I've been searching around a bunch to try and find some more in the Java/Enterprisey realms.

**Comment by steven7mwesigwa** [comment]
@Adron  Unfortunately, i haven't found much. But sure, i will submit when i find one.

**Comment by tedyoung** [comment]
Just found this repo, so will be submitting my Java stream (twitch.tv/jitterted).

**Comment by mblayman** [comment]
I'll welcome any Java streamers that people manage to find. With adding Ted to the list, I'm going to close this one.
