### ISSUE TITLE
Dead branches

### ISSUE THREAD

**Issue by surlydev** [bnb/awesome-developer-streams#178]
There are some dead branches that could be removed, such as :- 
bnb/add-brian
bnb/add-feross
bnb/add-kyle
bnb/add-thlorenz
bnb/add-yosh
revert-74-master

Also, the branches for the PR's I have raised this morning (after they have been merged).

**Comment by mblayman** [comment]
I'm not really concerned with dead branches, but I wouldn't be opposed to them being cleaned up. Perhaps @bnb can raise your permissions to be able to modify the repo.

@bnb, @surlydev has made some good contributions and would make a good additional maintainer, IMO.

**Comment by bnb** [comment]
Per your recommendation @mblayman, I've added @surlydev as a collaborator.

**Comment by surlydev** [comment]
Thank you for your vote of confidence guys.

**Comment by bnb** [comment]
Also: feel free to delete any dead branches! I have no attachment to them ❤️

**Comment by surlydev** [comment]
Cleaned them up. 

FYI the command was ... git push upstream :{old-branch-name}

Yes, the colon was required. Thanks to AdmiringWorm on Twitch.

**Comment by AdmiringWorm** [comment]
You may also delete multiple branches at the same time if you need that in the future.
```
git push upstream :{branch-1} :{branch-2} :{branch-3}
```

You may not need that now, but just letting you know.

**Comment by ChaelCodes** [comment]
You can also set up your repo to automatically delete branches after merging a PR: https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by bnb** [comment]
@ChaelCodes I've turned that on 👍

**Comment by ChaelCodes** [comment]
Yay! I'm glad you liked the suggestion.
