### ISSUE TITLE
Broken Twitch URLs under some names

### ISSUE THREAD

**Issue by hoborm** [bnb/awesome-developer-streams#278]
Hi!

I've found some broken URLs under these people:
- https://github.com/bnb/awesome-developer-streams#bobby-johnson
- https://github.com/bnb/awesome-developer-streams#adron-hall
- https://github.com/bnb/awesome-developer-streams#calvin-allen--coding-with-calvin (Firefox warns for potential security issue & twitch URL actually redirects to https://luv2.dev/live)
- https://github.com/bnb/awesome-developer-streams#ninjabunny9000

I was looking for C# streams, I did not intent to cover every broken URL in the document only the ones I was interested in.

Cheers.

**Comment by 1kevgriff** [comment]
Nothing to add, but thanks for the follow!
