### ISSUE TITLE
D. C. Rockwell is missing

### ISSUE THREAD

**Issue by Mouvedia** [bnb/awesome-developer-streams#73]
https://www.twitch.tv/automateallthethings
TDD, javascript

**Comment by bnb** [comment]
@Mouvedia hey there! 👋

Could you submit a PR to add D.C. Rockwell? Would love to have them on the list but am not familiar enough with them to feel comfortable adding them myself 😅

**Comment by Mouvedia** [comment]
He doesn't do live coding anymore; too bad it used to be great.
